name: Deploy to AWS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Add AWS host to known hosts
              run: ssh-keyscan -t rsa ${{ secrets.AWS_IP }} >> ~/.ssh/known_hosts

            - name: SSH and deploy to AWS
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  AWS_IP: ${{ secrets.AWS_IP }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${AWS_IP} "sudo bash ~/deploy.sh"
