name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Add EC2 host to known hosts
              run: ssh-keyscan -H 3.110.220.176 >> ~/.ssh/known_hosts

            - name: Deploy to EC2
              run: |
                  # Replace the following with your deployment script or commands
                  ssh ubuntu@3.110.220.176 << EOF
                  cd /home/ubuntu/github_code_base
                  git pull origin main
                  ./deploy.sh
                  EOF
