name: Deploy to AWS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install SSH key
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Install rsync
              run: sudo apt-get install -y rsync

            - name: Deploy code to AWS instance
              run: rsync -r --delete-after --quiet $GITHUB_WORKSPACE/ ubuntu@${{secrets.AWS_IP}}:/home/ubuntu/myapp/
