name: Deploy to AWS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: SSH and deploy to AWS
              env:
                  SH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
              run: |
                  echo "$SSH_PRIVATE_KEY" > keyfile
                  chmod 600 keyfile
                  mkdir -p ~/.ssh
                  cp known_hosts ~/.ssh/known_hosts
                  ssh -t -i keyfile ubuntu@${{secrets.AWS_IP}} "sudo bash ~/deploy.sh"
